#! /bin/bundle
# -*- mode: ruby; coding: utf-8 -*-

# As far as I read the implementation of brew bundle, this file is
# `instane_eval`ed.  Feel free to write any dangerous ruby things
# here.

ENV['HOMEBREW_MAKE_JOBS'] = '5'

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/command-not-found'
tap 'homebrew/core'
tap 'homebrew/cask-fonts'
tap 'homebrew/services'
tap 'mike-engel/jwt-cli'

brew 'actionlint'
brew 'awscli'
brew 'circleci'
brew 'coreutils'
brew 'doxygen'
brew 'findutils'
brew 'gawk'
brew 'gettext'
brew 'gh'
brew 'ghq'
brew 'gist'
brew 'git-filter-repo'
brew 'git-lfs'
brew 'git'
brew 'gitlab-runner', restart_service: true
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnu-time'
brew 'gnupg'
brew 'go'
brew 'graphviz'
brew 'grep'
brew 'gzip'
brew 'hub'
brew 'imagemagick'
brew 'jq'
brew 'keychain'
brew 'less'
brew 'lsof'
brew 'lv'
brew 'make'
brew 'mas'
brew 'nkf'
brew 'node-build'
brew 'nodenv'
brew 'openssh'
brew 'parallel'
brew 'pcre'
brew 'pigz'
brew 'pixz'
brew 'pstree'
brew 'pyenv'
brew 'rbenv'
brew 'rsync'
brew 'ruby-build'
brew 'rustup-init'
brew 'shared-mime-info'
brew 'shellcheck'
brew 'sl'
brew 'telnet'
brew 'tfenv'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'xz'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
brew 'zsh'

brew 'mike-engel/jwt-cli/jwt-cli'

cask_args appdir: "~/Applications"

cask 'font-inconsolata'
cask 'font-noto-sans'
cask 'font-noto-serif'

cask 'discord'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'gimp'
cask 'google-chrome'
cask 'keepingyouawake'
cask 'rustdesk'
cask 'session-manager-plugin'
cask 'slack'
cask 'visual-studio-code'
cask 'zoom'
cask 'emacs'
cask 'wireshark' # or 'wireshark-chmodbpf'

mas 'Bitwarden', id: 1352778147
mas 'Slack', id: 803453959
mas 'Yubico Authenticator', id: 1497506650
