#! /bin/bash
# minimal setup, .bashrc/.bash_profile/.bash_login are symlinks to this file.

export XDG_CONFIG_HOME=~/data/etc
export XDG_CACHE_HOME=~/data/cache
export XDG_DATA_HOME=~/data/share
export HISTFILE=~/data/etc/bash/history
export RBENV_ROOT=$XDG_CONFIG_HOME/rbenv
if [ -d ~/Library/Python/*/bin ]; then
    export PATH=$(echo ~/Library/Python/*/bin):$PATH
fi
